DROP TABLE IF EXISTS finance_analytics_dm.dwd_transactions;
CREATE TABLE IF NOT EXISTS finance_analytics_dm.dwd_transactions (
    transaction_id BIGINT NULL,
    account_id BIGINT NULL,
    customer_id BIGINT NULL,
    merchant_id BIGINT NULL,
    transaction_date DATETIME NULL,
    transaction_year BIGINT NULL,
    transaction_month BIGINT NULL,
    transaction_day BIGINT NULL,
    transaction_hour BIGINT NULL,
    day_of_week BIGINT NULL,
    is_weekend BOOLEAN NULL,
    is_late_night BOOLEAN NULL,
    transaction_type STRING NULL,
    amount DECIMAL(18,4) NULL,
    amount_abs DECIMAL(18,4) NULL,
    transaction_direction STRING NULL,
    currency STRING NULL,
    channel STRING NULL,
    merchant_category STRING NULL,
    mcc_code STRING NULL,
    description STRING NULL,
    is_fraud BOOLEAN NULL,
    fraud_score DECIMAL(18,4) NULL,
    fraud_risk_category STRING NULL,
    is_high_value BOOLEAN NULL,
    location_city STRING NULL,
    location_state STRING NULL,
    location_country STRING NULL,
    latitude DECIMAL(18,4) NULL,
    longitude DECIMAL(18,4) NULL,
    is_international BOOLEAN NULL,
    device_id STRING NULL,
    ip_address STRING NULL,
    authorization_code STRING NULL,
    card_last_four STRING NULL,
    is_recurring BOOLEAN NULL,
    hour_of_day BIGINT NULL,
    weekend_flag BOOLEAN NULL,
    distance_from_home_km STRING NULL,
    merchant_risk_score DECIMAL(18,4) NULL,
    velocity_24h BIGINT NULL,
    amount_deviation_score DECIMAL(18,4) NULL,
    processing_time_ms STRING NULL,
    decline_reason STRING NULL,
    transaction_status STRING NULL,
    updated_at DATETIME NULL
) ENGINE=OLAP
DUPLICATE KEY(transaction_id)
DISTRIBUTED BY HASH(transaction_id) BUCKETS 1
PROPERTIES (
    "replication_num" = "1"
);
