DROP TABLE IF EXISTS finance_analytics_dm.dws_transactions;
CREATE TABLE IF NOT EXISTS finance_analytics_dm.dws_transactions (
    transaction_id BIGINT NULL,
    transaction_key CHAR(32) NULL,
    customer_key CHAR(32) NULL,
    account_key CHAR(32) NULL,
    merchant_key CHAR(32) NULL,
    date_key CHAR(32) NULL,
    transaction_date DATETIME NULL,
    transaction_year BIGINT NULL,
    transaction_month BIGINT NULL,
    transaction_day BIGINT NULL,
    transaction_hour BIGINT NULL,
    day_of_week BIGINT NULL,
    is_weekend BOOLEAN NULL,
    is_late_night BOOLEAN NULL,
    transaction_type STRING NULL,
    transaction_direction STRING NULL,
    currency STRING NULL,
    channel STRING NULL,
    merchant_category STRING NULL,
    mcc_code STRING NULL,
    description STRING NULL,
    location_city STRING NULL,
    location_state STRING NULL,
    location_country STRING NULL,
    is_international BOOLEAN NULL,
    device_id STRING NULL,
    authorization_code STRING NULL,
    card_last_four STRING NULL,
    is_recurring BOOLEAN NULL,
    transaction_status STRING NULL,
    decline_reason STRING NULL,
    fraud_risk_category STRING NULL,
    transaction_amount DECIMAL(18,4) NULL,
    transaction_amount_abs DECIMAL(18,4) NULL,
    fraud_score DECIMAL(18,4) NULL,
    distance_from_home_km STRING NULL,
    merchant_risk_score DECIMAL(18,4) NULL,
    velocity_24h BIGINT NULL,
    amount_deviation_score DECIMAL(18,4) NULL,
    processing_time_ms STRING NULL,
    is_fraud_flag BOOLEAN NULL,
    is_high_value_flag BOOLEAN NULL,
    is_high_risk_flag BOOLEAN NULL,
    is_declined_flag BOOLEAN NULL,
    fraud_amount DECIMAL(18,4) NULL,
    declined_count BIGINT NULL,
    transaction_count BIGINT NULL,
    dbt_updated_at DATETIME NULL
) ENGINE=OLAP
DUPLICATE KEY(transaction_id)
DISTRIBUTED BY HASH(transaction_id) BUCKETS 1
PROPERTIES (
    "replication_num" = "1"
);
